### ISSUE TITLE
error on seadrive 1.0.3 install on windows (requires restart)

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#116] opened 2019-03-26 08:20 UTC
When trying to install from Seadrive 1.0.1 after downloading and running the executable (because it is not possible to update from GUI as described in issue #98) I get the following error :

![seadrive-1 0 3-setup-crash](https://user-images.githubusercontent.com/18724661/54981144-e153a980-4fa7-11e9-98c9-9e64a24b31d1.png)

After restart, a window pops up asking to install Seadrive, and the installation succeeds this time.

It would be nice to inform the user to restart rather showing an error (or to install without restart at all).

Installer is run on user session who is admin, also tried with "Run as administrator" but same error.

- Windows 1809
- Seadrive 1.0.3

**Comment by monkeydri** [comment] 2019-03-27 06:57
[SeaDrive_1.0.3_20190326200513.log](https://github.com/haiwen/seadrive-gui/files/3011896/SeaDrive_1.0.3_20190326200513.log)

**Comment by killing** [comment] 2019-04-01 05:24
This issue is known but we haven't found the root cause of it. A quick fix is to open command line  (cmd) on Windows and run the following command to uninstall existing SeaDrive.

```
msiexec /x {210D8860-21E3-4A3C-A952-DD44A497BA82}
```

**Comment by killing** [comment] 2019-04-28 12:14
This is due to the fact that the certificate we use to sign 1.0.1 or older expired some time ago. This prevents Windows from uninstalling it. (Yeah Windows doesn't allow you to uninstall software that is not "legal".) After new versions there should be no such problems.

**Comment by monkeydri** [comment] 2019-04-28 19:35
Alright Thank you very much for the feedback, I just installed seadrive 1.0.4 and had the same error, I will close the issue if issue is fixed when trying to update to next version.ame error when updating from

**Comment by didrip** [comment] 2019-07-11 11:52
Error persists when trying to install seadrive 1.0.6
There is no error shown after restart but still, Seadrive is not installed properly (listed in Settings > Apps) but no Seadrive Folder in C:\Program Files. Needs to run the installer again.

- seadrive 1.0.6
- Windows 1809

**Closed** 2020-09-17 06:46 UTC
