### ISSUE TITLE
Seadrive fails overwriting files

### ISSUE THREAD

**Issue by denis-roy** [haiwen/seadrive-gui#31] opened 2017-06-17 14:45 UTC
## VERSIONS

Windows 10 Enterprise LTSB
Seafile 6.0.9
Seadrive 0.7.0

## PROBLEM

When trying to overwrite a file:

![seafile overwriting](https://user-images.githubusercontent.com/3801326/27253819-ad8aaa1a-5349-11e7-9929-b127dc347608.png)

This happens to me everytime I want to merge two folders together where both happens to have common files and I choose to overwrite the destination (Seadrive) with the source (Hard drive). No matter how big or small the files are.

**Comment by killing** [comment] 2017-08-20 07:48
Can you post the log file seadrive.log when this error happens? You can find the log files by right clicking on the seadrive icon in system notification area. There is a "open log folder" menu item.

**Comment by holantomas** [comment] 2017-09-19 11:51
Same problem.
I can't post log file cause personal data but I found some errors. 

This is one example
```
[09/18/17 16:39:34] http-tx-mgr.c(3443): Bad response code for POST https://seafile.xxxxxxxx.cz/seafhttp/repo/34118c48-6863-432f-be82-939f2e57b4f1/check-blocks/: 0.
[09/18/17 16:39:34] http-tx-mgr.c(3623): Failed to get needed block list for file xxxxxxx.pdf
[09/18/17 16:39:34] http-tx-mgr.c(875): libcurl failed to PUT https://seafile.xxxxxxxx.cz/seafhttp/repo/34118c48-6863-432f-be82-939f2e57b4f1/block/f837709c007295011604256d8b3bc7fd5c34d5a8: Operation was aborted by an application callback.
[09/18/17 16:39:34] http-tx-mgr.c(875): libcurl failed to PUT https://seafile.xxxxxxxx.cz/seafhttp/repo/34118c48-6863-432f-be82-939f2e57b4f1/block/0e702083a05a3ed621fddf06839bed63044ab3a8: Operation was aborted by an application callback.
[09/18/17 16:39:34] http-tx-mgr.c(1145): Transfer repo '34118c48': ('normal', 'data') --> ('error', 'finished')
[09/18/17 16:39:34] sync-mgr.c(595): Repo 'xxxxx' sync state transition from uploading to 'error': 'Error occured in upload.'.
[09/18/17 16:40:04] sync-mgr.c(561): Repo 'xxxxx' sync state transition from 'synchronized' to 'uploading'.
```

**Comment by holantomas** [comment] 2017-10-09 10:38
@killing ping

**Comment by killing** [comment] 2017-10-10 09:24
@holantomas The log message you post is network error and should not be related to the error you saw. How do you reproduce the problem?

**Comment by holantomas** [comment] 2017-10-10 09:33
@killing 

1. Copy some new folder with files into library over SeaDrive by one turn(Drag&Drop whole folder)
2. After sync complete(I tried overwrite after couple of hours) do step 1.

This happend on windows. Folder size doesn't matter. This happend from 100MB to 80GB.
The log I post is only type of error. Every error in log is same, but different library/file.
My idea is that it can cause by some characters or spaces in files/folders name. But didn't test it.
You can try, there are czech characters ěščřžýáíéňó.

PS: Never see this error when copying only one file.

**Comment by holantomas** [comment] 2017-10-27 05:48
@killing 
> @holantomas The log message you post is network error and should not be related to the error you saw. How do you reproduce the problem?

FYI there's no network error during this message in log. And this message is produced every time when message from first post show.

**Comment by freeplant** [comment] 2017-11-07 02:22
@holantomas I can't reproduce the problem yesterday. Can you share with me such a folder?

**Comment by holantomas** [comment] 2017-11-07 05:12
@freeplant I'm going to try it on new version of seadrive. Maybe it's solved by different mount method. 
Sorry but I cannot share folder with you cause of company and customers data.

**Comment by holantomas** [comment] 2017-11-07 06:57
@freeplant Tested it and it steal doing. I initialize lastes seadrive client (no seadriver client was on computer before). Just copy files (Windows and Linux ISO files + one exe file) by drag&drop to computer. After that, did restart of computer for sure and drag&drop files from computer back to seadrive(S:/). It show immediately error from first post of this issue on all files. No file was copied/overwriten.

**Comment by freeplant** [comment] 2017-11-07 08:58
Do you have special characters in these file names?

**Comment by freeplant** [comment] 2017-11-07 09:01
Okay, I can reproduce the problem now.

**Comment by holantomas** [comment] 2017-11-07 09:04
I tried to find some log (windows event viewer) but there's nothing. Just there's nothing to help debug, only error below.

Here is file list that I tried last overwrite:
```
07. 11. 2017  06:37    <DIR>          .
07. 11. 2017  06:37    <DIR>          ..
23. 10. 2017  09:54         1 599 179 callrecorder9.apk
17. 08. 2017  12:08     2 825 566 208 MS_Office_2016__Home_and_Business.img
23. 08. 2017  12:22       134 351 488 nod32_installer.exe
07. 09. 2017  05:19        15 702 528 pinya_guard.msi
17. 08. 2017  11:57     1 587 609 600 ubuntu-16.04.3-desktop-amd64.iso
17. 08. 2017  12:48     3 136 217 088 Win10_1703_Czech_x32.iso
17. 08. 2017  12:31     4 241 483 776 Win10_1703_Czech_x64.iso
22. 08. 2017  10:51     3 194 191 872 Win7_Pro_SP1_Czech_x64.iso
               8 File(s) 15 136 721 739 bytes
               2 Dir(s)  97 890 471 936 bytes free
```

**Comment by freeplant** [comment] 2017-11-09 12:52
The fix will be included in the next release.

**Closed by freeplant** 2017-11-09 12:52 UTC

**Comment by freeplant** [comment] 2017-11-10 03:46
The new 0.8.2 version is ready.

**Comment by denis-roy** [comment] 2017-11-12 01:19
@holantomas: Thank you for taking the time to follow up on this!

@freeplant, @killing: Thanks for fixing this.

**Comment by holantomas** [comment] 2017-11-12 09:10
@freeplant Can confirm fixed issue
