### ISSUE TITLE
Adobe Reader Freezing

### ISSUE THREAD

**Issue by holantomas** [haiwen/seadrive-gui#47] opened 2017-12-14 08:10 UTC
Hi,
from september when we started using SeaDrive we have problem with Adobe Reader.

Sometimes it freeze on loading document and cannot be killed over task manager. Only after stop SeaDrive (normally right-click on icon in tray and "exit") it close. Some times Reader doesn't open so we try it again and after look in TaskManager there are a few Adobe Reader proccesses which halting CPU (30-60% CPU usage). Again cannot be killed, only after stop SeaDrive klient. I think it's somewhere in loding/donwloading proccess or in log file path. There are no connection between PDF, a lot of sources and their content.

I wait for this moment to grab as much as information is posible. But that's all. No error in SeaDrive logs even extended added a few version ago. No system log, no error message. Just problem :D

Windows 10 with Fall Creators update
SeaDrive 0.8.4
PDF was uploaded/synced few weeks ago

There is path for example
`S:\QwertCr\Fghj 4 Poiu s.r.o\MNBVCZXLKJH sd dfgseggbscjí\MKGURNÍME\Lkstň, Vix - mkszxpí BVFŽOP ČP a.s - Okvaruveá Klřqse\Burdpv Qxtdáčjklýq\dasdsa a dsds dsxq.PDF`

**Comment by freeplant** [comment] 2017-12-14 08:57
I don't have such a problem with Adobe Acrobat Reader DC 2018.009.20044. What version do you use? What is the size of the PDF file? Can you try first download the file then open via Adobe Reader? In version 0.8.4, there is a context menu "Seafile->Download"

**Comment by holantomas** [comment] 2017-12-14 09:50
@freeplant 2018.009.20050, 152kB
As I said on forum, there are problems with sync which damaged all other sync. I found that this files was inserted at 1.12.2017 but they are still not synced (check over Seahub). There are no synced whole directories (where failing PDF are). But this is other problem.

My guess is that, if file is not fully synced this problem happend.

**Comment by freeplant** [comment] 2017-12-14 10:26
@holantomas Thanks for the information. What do you mean by not synced? Can you send me the original forum post?

**Comment by holantomas** [comment] 2017-12-14 10:32
@freeplant https://forum.seafile.com/t/seadrive-is-not-production-ready/4395 in my first post is list. This is mentioned in first item.

And it's mean that if there is some sync error in SeaDrive on some folder it's drop syncing for whole library. For us there is problem that sync error was created before 0.8.3 so there's no more error logs. 
Files are just sit in computer/dokan. They don't have SeaDrive status icon in explorer for days/weeks after insert.

**Comment by killing** [comment] 2017-12-15 06:00
@holantomas Can you send me seadrive.log on the problematic client? Please upload it to https://download.seafile.com/u/d/5cd866f6eb6741999afc/

**Comment by killing** [comment] 2017-12-15 06:41
About the not-uploading problem, does restarting SeaDrive solve it?

**Comment by holantomas** [comment] 2017-12-15 09:35
@killing Uploaded all 4 files

No whole computers was restarted many times. SeaDrive only too. I think there are some sync errors from older versions which blocking that. Can you add some Force resync feature to SeaDrive? Which will scan and upload all non-upload files? May it will help to solv this. 

And yes I did reinstall on all PCs when upgrading to 0.8.4 as manual saying.

**Comment by killing** [comment] 2017-12-18 13:13
@holantomas From you log, I find that the reason for not syncing is similar to this thread: https://forum.seafile.com/t/problems-with-cut-and-paste-folders-in-seadrive/2146 . But this was an old bug which has been fixed long ago. Have you ever used that old version?

The solution would be to logout the account and login again. That would clear the syncing status.

**Comment by killing** [comment] 2017-12-18 13:18
Before logging out, can you send me a few internal database files for analysis?

/c/users/username/seadrive/data/branch.db
/c/users/username/seadrive/data/journals/fbc7919xxxx.db

These files can help me fix the bug if there is one.

**Comment by holantomas** [comment] 2017-12-18 13:21
Ok will send tomorrow.

**Comment by holantomas** [comment] 2017-12-19 07:58
@killing I uploaded these files to link you provide above.

**Comment by killing** [comment] 2017-12-20 09:40
@holantomas Thanks for the logs. From the information you provided, I can isolate the operations that causes your stop syncing issue. The operation was simply editing and saving a .doc file. I cannot reproduce the issue using the same operation with the current version. Your operation was back to 2017/10/19 and may be made by some old version.

After looking at the change history of SeaDrive, I find that we fixed a similar bug with this operation in 0.6.0 version. Have you ever used versions older than 0.6.0?

**Comment by holantomas** [comment] 2017-12-20 09:45
@killing yes, I know there was problem with this. But after update it start working so nobody have problem.

**Comment by holantomas** [comment] 2017-12-20 09:47
I think I can close this issue, or do you need some more info?

**Comment by killing** [comment] 2017-12-20 10:16
OK thanks. We can close the issue.

**Closed by killing** 2017-12-20 10:16 UTC
