### ISSUE TITLE
Unable to set permissions or execute files

### ISSUE THREAD

**Issue by aarononeal** [haiwen/seadrive-gui#168] opened 2020-01-27 07:05 UTC
Running `chmod +x script.sh` has no effect so it is not possible to set permissions to execute files from the drive.

**Comment by andreasley** [comment] 2020-04-27 11:13
Seems to be a duplicate of #137

**Comment by killing** [comment] 2020-09-17 06:40
x permission is currently not supported.

**Closed by killing** 2020-09-17 06:40 UTC
